### ISSUE TITLE
How to run a worker consuming tokio-cron indefinitely

### ISSUE THREAD

**Issue by jonasms** [kurtbuilds/tokio-cron#1]
I have a question about using this in production that I think would be helpful to create a simple example for (happy to contribute that).

I have the following code (simplified):
```
pub async fn run_on_schedule(config: Settings) -> Result<(), anyhow::Error> {
    let mut scheduler = Scheduler::utc();

    let daily_config = config.clone();

    // Every day @ 8 AM MDT
    scheduler.add(Job::named("daily-report-job", daily("14"), move || {
        let c = daily_config.clone();

        async move {
            let mut worker = ReportWorker::new(c).await;

            try_execute_task(&mut worker, Cadence::Day)
                .await
                .expect("Failed to execute daily task");
        }
    }));
};
```

When I run, the scheduler gets set up but the app terminates right after.

What's a good way to keep the app running?

The following solution came to mind; appending
```
loop {
   tokio::time::sleep(std::time::Duration::from_secs(60)).await;
}
```

after setting up the scheduler.

EDIT:
Will probably use an interval but same concept.

**Comment by kurtbuilds** [comment]
Yup, that absolutely works. You should also be able to do:

```tokio::time::sleep_until(DateTime::<Utc>::MAX_UTC).await```
