### ISSUE TITLE
Add a licence?

### ISSUE THREAD

**Issue by joshsharp** [kurtbuilds/tokio-cron#2]
Hi! Thanks for making this, it's exactly what I'm looking for. I'd like to use it in production, and I see it's listed as MIT-licenced on crates.io, but there's no licence file listed in the repo, so I can't link back to it or include it, which is a requirement for using MIT-licenced stuff. Could you add it here? Thanks!

**Comment by kurtbuilds** [comment]
Sorry for delay, just updated
